### ISSUE TITLE
Mybatis対応エラー1

### ISSUE THREAD

**Issue by sprngTst001** [thayashi131050/spring-batch-sample#11]
・エラーログ
[xml読み取りエラー.txt](https://github.com/thayashi131050/spring-batch-sample/files/4607534/xml.txt)
※エラー文に
　Mapped Statements collection does not contain value for ～（87行目）
　とあるので、xml内の読み取れていない状態だと判断しました。

・ファイル構造
[tree.txt](https://github.com/thayashi131050/spring-batch-sample/files/4607552/tree.txt)
※不要かもしれません。

・ファイル
https://github.com/sprngTst001/check01
※ファイルも合わせてアップロードしてみました。(確認用にリポジトリを作りました。)
　ソース内にメモ書き等ありますが無視してください。

**Comment by thayashi131050** [comment]
XMLファイルが読み込まれなかった理由は、XMLファイルがMapperのインタフェースと同じクラスパスに配置されていないためです。
誤：`resources/PersonMapper.xml`
正：`resources/com/example/demo2/PersonMapper.xml`

＜参考＞
[Mapper の登録](http://mybatis.org/spring/ja/mappers.html)

---
また、SQLの取得結果をPersonクラスにマッピングする部分も問題がありました。
※旧`PersonMapper.java`における、ResultSetをPersonに変換する部分
`application.properties`に追加設定が必要です。
```
mybatis.configuration.map-underscore-to-camel-case=true ・・・１
mybatis.configuration.auto-mapping-unknown-column-behavior=WARNING ・・・２
```
MyBatisにはResultSetのカラムをJavaクラスのプロパティに自動的にマッピングする機能があります。
ただし、今回のケース(テーブルのカラム名はスネークケース、Personクラスのプロパティ名はキャメルケース)のような場合は、カラム名とプロパティ名を単純に紐づけられないため、名前の変換設定が必要です。
上記１の設定で、スネークケースをキャメルケースに変換する機能を有効化しています。デフォルトは無効`false`です。
２は、自動マッピングでカラムとプロパティの紐づけができなかった場合にワーニングを出力する設定です。こちらのデフォルト設定は何もしない`NONE`です。

＜参考＞
[自動マッピング](https://mybatis.org/mybatis-3/ja/sqlmap-xml.html#a.E8.87.AA.E5.8B.95.E3.83.9E.E3.83.83.E3.83.94.E3.83.B3.E3.82.B0)
[MyBatisの設定](https://mybatis.org/mybatis-3/ja/configuration.html#settings)

**Comment by sprngTst001** [comment]
無事、動作しました。
ご説明ありがとうございました！
