### ISSUE TITLE
Spring Bootのテストでバッチ処理が2度実行される

### ISSUE THREAD

**Issue by thayashi131050** [thayashi131050/spring-batch-sample#16]
b6f1c87612c9373d6c6fed44cadba142d25665c6 のコミットでテストを実行すると、ログにバッチ処理の実行結果が2回出力される。
この動きは仕様なのか調査をお願いします。

**Comment by sprngTst001** [comment]
テストメソッドでバッチを起動するためにBatchProcessingApplication.mainを呼び出していましたが、呼び出さなくてもバッチは起動するようです。
```
    public void test() throws Exception{
        BatchProcessingApplication.main(new String[] {""});   // 不要
    }
```
余分にBatchProcessingApplicationを呼び出していたため2度バッチ処理が行われていました。
対応は次回のpullRequestに組み込みます。

**Comment by thayashi131050** [comment]
プルリクエストの取り込みをもってクローズとします。
修正のコミットコメントに`fix #16`を含めてください。
